# Generated by Django 4.2.5 on 2023-10-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background1', models.ImageField(upload_to='images', verbose_name='Background 1')),
                ('background2', models.ImageField(upload_to='images', verbose_name='Background 2')),
                ('background3', models.ImageField(upload_to='images', verbose_name='Background 3')),
                ('subtitle', models.CharField(max_length=50, verbose_name='Subtitle')),
                ('title', models.CharField(max_length=40, verbose_name='Title')),
                ('text', models.CharField(max_length=80, verbose_name='Text')),
                ('button1', models.CharField(max_length=30, verbose_name='Button 1')),
                ('button2', models.CharField(max_length=30, verbose_name='Button 2')),
            ],
            options={
                'verbose_name': 'Home',
                'verbose_name_plural': 'Home',
            },
        ),
    ]
