# Generated by Django 4.2.5 on 2023-10-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos', verbose_name='Video')),
                ('video_title1', models.CharField(max_length=30, verbose_name='Video Title 1')),
                ('video_title2', models.CharField(max_length=30, verbose_name='Video Title 2')),
                ('subtitle', models.CharField(max_length=40, verbose_name='Subtitle')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('text1', models.TextField(verbose_name='Text 1')),
                ('text2', models.TextField(verbose_name='Text 2')),
                ('button', models.CharField(max_length=30, verbose_name='Button')),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'About',
            },
        ),
    ]
