# Generated by Django 4.2.5 on 2023-10-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_subtitle', models.CharField(max_length=50, verbose_name='Member Subtitle')),
                ('member_title', models.CharField(max_length=40, verbose_name='Member title')),
                ('menu_subtitle1', models.CharField(max_length=50, verbose_name='Menu Subtitle 1')),
                ('menu_title1', models.CharField(max_length=40, verbose_name='Menu title 1')),
                ('menu_subtitle2', models.CharField(max_length=50, verbose_name='Menu Subtitle 2')),
                ('menu_title2', models.CharField(max_length=40, verbose_name='Menu title 2')),
                ('review_subtitle', models.CharField(max_length=50, verbose_name='Review Subtitle')),
                ('review_title', models.CharField(max_length=40, verbose_name='Review title')),
                ('contact_subtitle', models.CharField(max_length=50, verbose_name='Contact Subtitle')),
                ('contact_title', models.CharField(max_length=40, verbose_name='Contact title')),
                ('reservation_subtitle', models.CharField(max_length=50, verbose_name='Reservation Subtitle')),
                ('reservation_title', models.CharField(max_length=40, verbose_name='Reservation title')),
            ],
        ),
    ]
