# Generated by Django 4.2.5 on 2023-10-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images', verbose_name='Image')),
                ('name', models.CharField(max_length=40, verbose_name='Name')),
                ('position', models.CharField(max_length=30, verbose_name='Position')),
                ('text', models.TextField(verbose_name='Text')),
            ],
        ),
    ]
