# Generated by Django 4.2.5 on 2023-10-01 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='menu_subtitle1',
        ),
        migrations.RemoveField(
            model_name='title',
            name='menu_subtitle2',
        ),
        migrations.RemoveField(
            model_name='title',
            name='menu_title1',
        ),
        migrations.RemoveField(
            model_name='title',
            name='menu_title2',
        ),
    ]
