# Generated by Django 4.2.5 on 2023-10-01 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_title_menu_subtitle1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.ImageField(upload_to='images', verbose_name='Background')),
                ('menu_subtitle1', models.CharField(max_length=50, verbose_name='Menu Subtitle 1')),
                ('menu_title1', models.CharField(max_length=40, verbose_name='Menu title 1')),
                ('menu_subtitle2', models.CharField(max_length=50, verbose_name='Menu Subtitle 2')),
                ('menu_title2', models.CharField(max_length=40, verbose_name='Menu title 2')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menu',
            },
        ),
    ]
