# Generated by Django 4.2.5 on 2023-10-01 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(max_length=50, verbose_name='SubTitle')),
                ('title', models.CharField(max_length=40, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Menu Category',
                'verbose_name_plural': 'Menu Category',
            },
        ),
        migrations.RemoveField(
            model_name='menu',
            name='menu_subtitle1',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='menu_subtitle2',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='menu_title1',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='menu_title2',
        ),
        migrations.CreateModel(
            name='MenuContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('recommend', models.BooleanField(blank=True, verbose_name='Recommend')),
                ('price', models.FloatField(verbose_name='Price')),
                ('new_price', models.FloatField(verbose_name='New Price')),
                ('text', models.TextField(verbose_name='Text')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.menucategory')),
            ],
        ),
    ]
