# Generated by Django 4.2.5 on 2023-10-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_menucategory_remove_menu_menu_subtitle1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menucontent',
            name='new_price',
            field=models.FloatField(blank=True, verbose_name='New Price'),
        ),
    ]
