# Generated by Django 4.2.5 on 2023-10-01 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_menucontent_new_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menucontent',
            name='new_price',
            field=models.FloatField(blank=True, null=True, verbose_name='New Price'),
        ),
    ]
