# Generated by Django 4.2.5 on 2023-10-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.ImageField(upload_to='images', verbose_name='Background')),
                ('google_map', models.TextField(verbose_name='Google Map')),
                ('button', models.CharField(max_length=30, verbose_name='Button')),
            ],
        ),
    ]
