# Generated by Django 4.2.5 on 2023-10-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_footer_openhours'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, verbose_name='Name')),
                ('user_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('user_message', models.TextField(verbose_name='Message')),
            ],
        ),
    ]
