# Generated by Django 4.2.5 on 2023-10-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_reservationinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=60, verbose_name='Name')),
                ('user_phone', models.CharField(max_length=30, verbose_name='Phone Number')),
                ('user_time', models.TimeField(verbose_name='Time')),
                ('user_date', models.DateField(verbose_name='Date')),
                ('user_count', models.IntegerField(verbose_name='Count')),
                ('user_message', models.TextField(blank=True, null=True, verbose_name='Message')),
            ],
        ),
    ]
