# Generated by Django 4.2.5 on 2023-10-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_reservation_user_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='user_date',
            field=models.CharField(max_length=15, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user_time',
            field=models.CharField(max_length=8, verbose_name='Time'),
        ),
    ]
